### ISSUE TITLE
Not multithread safe

### ISSUE THREAD

**Issue by NiiloNeuvo** [arakelian/java-jq#10]
We're getting all sorts of strange behavior when running in a multithreaded environment doing load testing. I wrote a small test program just to run 500 threads and parsing the same JSON file on those threads. On my 4 core i7 laptop random parsing errors started appearing.

After creating a simple shared lock:
```   private static final Lock lock = new ReentrantLock();```

And wrapping all execute() calls with the lock all the parsing errors disappeared.
```         JqResponse response;
            lock.lock();
            try {
                response = request.execute();
            } finally {
                lock.unlock();
            }
```

My thoughts on how this should be fixed would just handle the locking in the execute() method inside java-jq. This does have a dramatic decrease in multithreaded performance, but at least the random error behaviour would go away.

**Comment by arakelian** [comment]
@NiiloNeuvo Guessing this is caused by thread-safety issues with JqLibrary / JNA interface. Let me run some tests, and if that's it, I'll add ability to create JqLibrary pool so we don't crash down to single thread.

**Comment by arakelian** [comment]
@NiiloNeuvo Might have to add the lock after all, see https://github.com/stedolan/jq/issues/120

**Comment by NiiloNeuvo** [comment]
Doesn't look promising. The lock is quick to add and quick to remove when (if ever) the jq library gets thread safe. 

We'll just launch more containers under Kubernetes to overcome this lack of multithreading support.

**Comment by arakelian** [comment]
I added the lock code. Release as part of version 1.1.0.  I just pushed to Maven Central, will be visible in a few hours.

**Comment by NiiloNeuvo** [comment]
Tested this with my test case and the fix works. Thanks for a quick fix.
