### ISSUE TITLE
How to merge files using java-jq

### ISSUE THREAD

**Issue by JagadeesanV** [arakelian/java-jq#13]
Hi,

I am trying to merge multiple json files and run deleting some nodes on the combined json before storing it as an output file.

How can I pass in the files names to the input method. 

I saw this can be achieved by something like 

jq -s '[.[][]]'*.json &gt; combine.json

Thanks.

**Comment by arakelian** [comment]
@JagadeesanV This library doesn't take multiple filenames. It's intended to handle a single input at a time.  No plans to change that, but if I'll take a PR to add support for that.
