### ISSUE TITLE
Enhancement request: Windows support

### ISSUE THREAD

**Issue by bgha-stibosystems** [arakelian/java-jq#2]
We are interested in using this , but it appears that there is no support for Windows. We are running linux in the docker containers, but we are developing on Linux, Mac, and Windows, and thus would like to be able to run unit tests on these platforms.

Are you considering added Windows support? Alternatively, could you give us hints to how to build the Windows 64-bit library of jq.

**Comment by arakelian** [comment]
@bgha-stibosystems I had problems getting a Windows compile working myself. I'd love to do it, just got busy. I'll give it another go this week.

**Comment by andrewv99** [comment]
Hi, any progress on Windows support ?

Thanks

**Comment by arakelian** [comment]
@andrewv99 I've had problems getting the support library to build in a Docker container.  I don't run Windows myself.  Still working on this as time permits

**Comment by mgsantositrs** [comment]
Any update on windows support?

**Comment by arakelian** [comment]
It's gonna happen in the next 2-3 weeks.  I need this for work now, so it'll be a priority.

**Comment by arakelian** [comment]
I haven't had luck with my Dockerized builds for Windows. Still trying as time permits.

**Comment by HoffiMuc** [comment]
any progress on this? windows support would be highly appreciated.

I still get: `Unsupported architecture: windows 10:amd64`

**Comment by arakelian** [comment]
Not yet.  I may release the Dockerfile I've been working on, and open it up for help.

**Comment by yrumax** [comment]
I'm on windows and would love to see this work. I was looking through the code and it doesn't seem too bad. I am available to help out. I'm not sure where to get the jq.dll file though.

**Comment by arakelian** [comment]
I've made a couple of attempts over the last year to get a Dockerfile doing jq builds for Windows, and generating the artifacts required for this project, but never got it working fully.  Going to close this, as this project is not very active, mainly because jq doesn't support multithreading, which made it more or less useless for my desired use case.

**Comment by arakelian** [comment]
For posterity, https://github.com/arakelian/java-jq/issues/10
