### ISSUE TITLE
java 8 compatibility

### ISSUE THREAD

**Issue by realtica** [arakelian/java-jq#27]
Amazing wrapper, 
Why the minimum java version is 11?
How can I compile for java 8?

**Comment by arakelian** [comment]
I have no interest in supporting Java 8 in this version. There is an older version of this library that supports it, but I don't intend to do so moving forward. Java 8 was release 2014, and is effectively EOL at this time, only receiving critical security updates. I understand that some folks are still forced to use it for work (I was one of those for a while), but even we moved on.
