### ISSUE TITLE
Not bug but feature request remove LOGGER dependency

### ISSUE THREAD

**Issue by itsme-narahari** [arakelian/java-jq#3]
This is a great piece of work.  Thank you.

Is it possible to remove references to the LOGGER stuff so we can reduce the dependency on logger stuff.  Just a suggestion, feel free to ignore.

One other point.
Currently there is no 0.9.5 tag available.  However the documentation in the README.md file says that.

Once again thank you for the great piece of work.

-Narahari

**Comment by arakelian** [comment]
@itsme-narahari I'm going to take a look at switching to JUL to remove the SLF4J dependency. Most of the stuff I'm logging is at trace level.

**Comment by arakelian** [comment]
Resolved with 0.10.1
