### ISSUE TITLE
invoque jq with params like argjson

### ISSUE THREAD

**Issue by crognon** [arakelian/java-jq#4]
Hi, 

thank you for this java jq wrapper.

how can one invoque JQ passing args like --argjson ?

thanks
Cyril

**Comment by arakelian** [comment]
Currently, JqLibrary has hardcoded a NOARGS array.

This is an easy enhancement.  I'll implement this.

**Comment by arakelian** [comment]
Wasn't as easy as I thought, but an update is coming soon.

**Comment by arakelian** [comment]
Resolved with version 0.10.0+

**Comment by valefix** [comment]
Can you please tell me how I can pass arguments?

I am interested in --raw-output

thank you for the wrapper!
