### ISSUE TITLE
Memory leak on jv_array?

### ISSUE THREAD

**Issue by srutouch** [arakelian/java-jq#7]
I have some memory leak problem, so that use jeprof to grab some hint...

Could you take look-at this?

---
At 161, JqRequest.java

        // for JQ 1.5, arguments is an array; this changes with JQ 1.6+
        Jv args = lib.jv_array();

**Comment by touchinno** [comment]
I add some code snippets to be tested.

In JqRequest.java

    private int jv_get_refcnt(final JqLibrary lib, final JqLibrary.Jv jv) {
        return lib.getLoader().getNativeLibrary().getFunction("jv_get_refcnt").invokeInt(new Object[] { jv });
    }

    private JqResponse parse(final Pointer state) {
    ...
        } finally {
            LOGGER.debug("Releasing callback");

            int refcnt = this.jv_get_refcnt(lib, args);
            if (refcnt > 0) {
                LOGGER.debug("[JQ] FREE jv_array {}", refcnt);
                for (int i = 0; i < refcnt; i++) {
                    lib.jv_free(args);
                }
            }

            lib.jq_set_error_cb(state, null, null);
        }

FYI.

**Comment by arakelian** [comment]
Thank you.  Will test this week.

**Comment by arakelian** [comment]
@touchinno Sorry this took so long to investigate.  This line has been changed now, with the move to JQ 1.6.  In JQ 1.5, jq uses an array of maps to pass arguments, now it just uses a single map.  I do believe there was an issue before, that was fixed.
